- name: variables from prompt
  hosts: local
  connection: local
  favcolor: blue
  vars_prompt: 
    - name: username
      prompt: "Please enter  username"
      private: false
    - name: password
      prompt: "Please enter  password"
      private: true
  tasks:
    - name: print credentials
      ansible.builtin.debug:
        msg: "Hello username is: {{ username }} {{ password }} {{ favcolor }}"